//! Private Unix IPC. No TCP fallback. Call bind only while owning the engine
//! data-directory lock; that lock serializes stale-socket recovery.
use crate::{RpcClient, RpcError, RpcService};
use std::{
    io,
    os::unix::fs::{DirBuilderExt, FileTypeExt, MetadataExt, PermissionsExt},
    path::{Path, PathBuf},
    sync::Arc,
};
use tokio::net::{UnixListener, UnixStream};

fn denied(message: &str) -> io::Error {
    io::Error::new(io::ErrorKind::PermissionDenied, message)
}

fn private_directory(path: &Path, create: bool) -> io::Result<()> {
    if create {
        let mut builder = std::fs::DirBuilder::new();
        builder.mode(0o700);
        match builder.create(path) {
            Ok(()) => {}
            Err(e) if e.kind() == io::ErrorKind::AlreadyExists => {}
            Err(e) => return Err(e),
        }
    }
    let meta = std::fs::symlink_metadata(path)?;
    if !meta.is_dir() || meta.uid() != unsafe { libc::geteuid() } || meta.mode() & 0o077 != 0 {
        return Err(denied(
            "IPC directory must be owned by this user with mode 0700",
        ));
    }
    Ok(())
}

fn validate_path(path: &Path, create: bool) -> io::Result<()> {
    use std::os::unix::ffi::OsStrExt;
    // Both macOS and Linux fit this bound, including the terminating NUL.
    if !path.is_absolute() || path.as_os_str().as_bytes().len() > 100 {
        return Err(io::Error::other(
            "IPC socket must have an absolute path of at most 100 bytes",
        ));
    }
    // Paths are generated by cypher-env, never arbitrary server-discovered URLs.
    let instance = path
        .parent()
        .ok_or_else(|| denied("missing IPC directory"))?;
    let root = instance
        .parent()
        .ok_or_else(|| denied("missing IPC root"))?;
    let expected = PathBuf::from(format!("/tmp/cypher-ipc-{}", unsafe { libc::geteuid() }));
    let key = instance.file_name().and_then(|s| s.to_str()).unwrap_or("");
    if root != expected
        || key.len() != 32
        || !key.bytes().all(|b| b.is_ascii_hexdigit())
        || path.file_name().and_then(|n| n.to_str()) != Some("engine.sock")
    {
        return Err(denied("invalid private IPC location"));
    }
    private_directory(root, create)?;
    private_directory(instance, create)
}

fn socket_metadata(path: &Path) -> io::Result<std::fs::Metadata> {
    let meta = std::fs::symlink_metadata(path)?;
    if !meta.file_type().is_socket()
        || meta.uid() != unsafe { libc::geteuid() }
        || meta.mode() & 0o077 != 0
    {
        return Err(denied(
            "IPC path is not a private socket owned by this user",
        ));
    }
    Ok(meta)
}

pub fn check_peer(stream: &UnixStream) -> io::Result<()> {
    if stream.peer_cred()?.uid() != unsafe { libc::geteuid() } {
        return Err(denied("IPC peer belongs to a different user"));
    }
    Ok(())
}

/// Absence/refused means stopped. Permission errors and malformed endpoints
/// must propagate rather than being interpreted as permission to start.
pub async fn probe_local(path: &Path) -> io::Result<bool> {
    match connect_stream(path).await {
        Ok(_) => Ok(true),
        Err(e)
            if matches!(
                e.kind(),
                io::ErrorKind::NotFound
                    | io::ErrorKind::ConnectionRefused
                    | io::ErrorKind::NotConnected
                    | io::ErrorKind::ConnectionReset
                    | io::ErrorKind::ConnectionAborted
            ) =>
        {
            Ok(false)
        }
        Err(e) => Err(e),
    }
}

async fn connect_stream(path: &Path) -> io::Result<UnixStream> {
    validate_path(path, false)?;
    socket_metadata(path)?;
    let stream = tokio::time::timeout(std::time::Duration::from_secs(2), UnixStream::connect(path))
        .await
        .map_err(|_| io::Error::new(io::ErrorKind::TimedOut, "IPC connect timed out"))??;
    check_peer(&stream)?;
    Ok(stream)
}

pub async fn connect_local(path: &Path) -> Result<RpcClient, RpcError> {
    use tokio_tungstenite::tungstenite::client::IntoClientRequest;
    let stream = connect_stream(path)
        .await
        .map_err(|e| RpcError::Transport(e.to_string()))?;
    let mut request = "ws://localhost/ipc"
        .into_client_request()
        .map_err(|e| RpcError::Transport(e.to_string()))?;
    request
        .headers_mut()
        .insert("sec-websocket-protocol", "cypher.rpc.v1".parse().unwrap());
    let (ws, response) = tokio::time::timeout(
        std::time::Duration::from_secs(5),
        tokio_tungstenite::client_async(request, stream),
    )
    .await
    .map_err(|_| RpcError::Transport("IPC handshake timed out".into()))?
    .map_err(|e| RpcError::Transport(e.to_string()))?;
    if response
        .headers()
        .get("sec-websocket-protocol")
        .and_then(|v| v.to_str().ok())
        != Some("cypher.rpc.v1")
    {
        return Err(RpcError::Transport(
            "unsupported Engine IPC protocol".into(),
        ));
    }
    Ok(crate::client::client_from_websocket(ws))
}

pub struct LocalListener {
    listener: UnixListener,
    path: PathBuf,
    identity: (u64, u64),
}

impl LocalListener {
    pub async fn accept(&self) -> io::Result<UnixStream> {
        let (stream, _) = self.listener.accept().await?;
        check_peer(&stream)?;
        Ok(stream)
    }
    pub async fn bind(path: &Path) -> io::Result<Self> {
        validate_path(path, true)?;
        match socket_metadata(path) {
            Ok(old) => {
                if probe_local(path).await? {
                    return Err(io::Error::new(
                        io::ErrorKind::AddrInUse,
                        "IPC engine is already running",
                    ));
                }
                let now = socket_metadata(path)?;
                if (old.dev(), old.ino()) != (now.dev(), now.ino()) {
                    return Err(denied("IPC socket changed during recovery"));
                }
                std::fs::remove_file(path)?;
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }
        let listener = UnixListener::bind(path)?;
        // The enclosing 0700 directory protects the bind-to-chmod interval.
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))?;
        let meta = socket_metadata(path)?;
        Ok(Self {
            listener,
            path: path.into(),
            identity: (meta.dev(), meta.ino()),
        })
    }

    pub async fn serve(self, service: Arc<dyn RpcService>) {
        let mut connections = tokio::task::JoinSet::new();
        loop {
            tokio::select! {
            _ = connections.join_next(), if !connections.is_empty() => {},
            accepted = self.accept(), if connections.len() < 128 => match accepted {
                Ok(stream) => {
                    connections.spawn(crate::server::serve_ws_socket(stream, service.clone()));
                }
                Err(error) => {
                    tracing::warn!(%error, "Unix IPC accept failed");
                    tokio::time::sleep(std::time::Duration::from_millis(100)).await;
                }
            }
            }
        }
    }
}

impl Drop for LocalListener {
    fn drop(&mut self) {
        if let Ok(meta) = socket_metadata(&self.path)
            && (meta.dev(), meta.ino()) == self.identity
        {
            let _ = std::fs::remove_file(&self.path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt;

    struct Service;
    #[async_trait::async_trait]
    impl RpcService for Service {
        async fn handle(
            &self,
            method: &str,
            params: serde_json::Value,
        ) -> Result<crate::RpcReply, RpcError> {
            match method {
                "Echo" => Ok(crate::RpcReply::Value(params)),
                "Count" => Ok(crate::RpcReply::Stream(
                    futures::stream::iter([serde_json::json!(0), serde_json::json!(1)]).boxed(),
                )),
                "Never" => Ok(crate::RpcReply::Stream(futures::stream::pending().boxed())),
                _ => Err(RpcError::UnknownMethod(method.into())),
            }
        }
    }

    fn path() -> (tempfile::TempDir, PathBuf) {
        let dir = tempfile::tempdir().unwrap();
        let path = cypher_env::ipc_socket(dir.path()).unwrap();
        (dir, path)
    }

    #[tokio::test]
    async fn private_socket_roundtrip_stream_and_disconnect() {
        let (_dir, path) = path();
        assert!(!probe_local(&path).await.unwrap());
        let listener = LocalListener::bind(&path).await.unwrap();
        assert_eq!(std::fs::metadata(&path).unwrap().mode() & 0o777, 0o600);
        let server = tokio::spawn(listener.serve(Arc::new(Service)));
        let client = connect_local(&path).await.unwrap();
        assert_eq!(
            client
                .call("Echo", serde_json::json!({"ok":true}))
                .await
                .unwrap(),
            serde_json::json!({"ok":true})
        );
        let mut items = client
            .subscribe("Count", serde_json::json!({}))
            .await
            .unwrap();
        assert_eq!(items.recv().await, Some(serde_json::json!(0)));
        assert_eq!(items.recv().await, Some(serde_json::json!(1)));
        assert_eq!(items.recv().await, None);
        let mut forever = client
            .subscribe("Never", serde_json::json!({}))
            .await
            .unwrap();
        server.abort();
        let _ = server.await;
        assert!(!path.exists());
        assert_eq!(
            tokio::time::timeout(std::time::Duration::from_secs(2), forever.recv())
                .await
                .unwrap(),
            None
        );
    }

    #[tokio::test]
    async fn live_socket_is_not_removed_and_instances_do_not_collide() {
        let (_a, a) = path();
        let (_b, b) = path();
        assert_ne!(a, b);
        let first = LocalListener::bind(&a).await.unwrap();
        let second = LocalListener::bind(&b).await.unwrap();
        assert!(LocalListener::bind(&a).await.is_err());
        assert!(probe_local(&a).await.unwrap());
        drop(first);
        assert!(probe_local(&b).await.unwrap());
        drop(second);
    }

    #[tokio::test]
    async fn local_protocol_and_origin_are_enforced() {
        use tokio_tungstenite::tungstenite::client::IntoClientRequest;
        let (_dir, path) = path();
        let server = tokio::spawn(
            LocalListener::bind(&path)
                .await
                .unwrap()
                .serve(Arc::new(Service)),
        );
        let stream = UnixStream::connect(&path).await.unwrap();
        assert!(
            tokio_tungstenite::client_async("ws://localhost/ipc", stream)
                .await
                .is_err()
        );
        let mut request = "ws://localhost/ipc".into_client_request().unwrap();
        request
            .headers_mut()
            .insert("sec-websocket-protocol", "cypher.rpc.v1".parse().unwrap());
        request
            .headers_mut()
            .insert("origin", "https://example.invalid".parse().unwrap());
        let stream = UnixStream::connect(&path).await.unwrap();
        assert!(
            tokio_tungstenite::client_async(request, stream)
                .await
                .is_err()
        );
        assert!(connect_local(&path).await.is_ok());
        server.abort();
        let _ = server.await;
    }

    #[tokio::test]
    async fn stale_socket_is_recovered_but_unknown_files_and_symlinks_are_not() {
        let (_dir, path) = path();
        drop(LocalListener::bind(&path).await.unwrap());
        let old = std::os::unix::net::UnixListener::bind(&path).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        drop(old); // crash-style leftover, unlike LocalListener's clean drop
        drop(LocalListener::bind(&path).await.unwrap());
        std::fs::write(&path, b"unrelated").unwrap();
        assert!(LocalListener::bind(&path).await.is_err());
        assert_eq!(std::fs::read(&path).unwrap(), b"unrelated");
        std::fs::remove_file(&path).unwrap();
        let outside = tempfile::NamedTempFile::new().unwrap();
        std::os::unix::fs::symlink(outside.path(), &path).unwrap();
        assert!(LocalListener::bind(&path).await.is_err());
        assert!(probe_local(&path).await.is_err());
        std::fs::remove_file(&path).unwrap();
        assert!(outside.path().exists());
    }

    #[tokio::test]
    async fn unsafe_permissions_and_replaced_socket_fail_closed() {
        let (_dir, path) = path();
        let old = LocalListener::bind(&path).await.unwrap();
        std::fs::set_permissions(
            path.parent().unwrap(),
            std::fs::Permissions::from_mode(0o755),
        )
        .unwrap();
        assert!(connect_local(&path).await.is_err());
        std::fs::set_permissions(
            path.parent().unwrap(),
            std::fs::Permissions::from_mode(0o700),
        )
        .unwrap();
        std::fs::remove_file(&path).unwrap();
        let replacement = std::os::unix::net::UnixListener::bind(&path).unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        drop(old);
        assert!(path.exists(), "old listener must not unlink a replacement");
        drop(replacement);
        std::fs::remove_file(path).unwrap();
    }

    #[tokio::test]
    #[ignore = "requires PI_PACKAGE_DIR pointing at the isolated Runtime and Node on PATH"]
    async fn node_bridge_uses_the_actual_rust_unix_rpc() {
        let (_dir, path) = path();
        let listener = LocalListener::bind(&path).await.unwrap();
        let server = tokio::spawn(listener.serve(Arc::new(Service)));
        let module = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .join("harness/src/pi/engine-client.mjs");
        let output = tokio::process::Command::new("node")
            .args([
                "--input-type=module",
                "-e",
                r#"
                import assert from 'node:assert/strict';
                import {pathToFileURL} from 'node:url';
                const {connectEngine} = await import(pathToFileURL(process.env.TEST_CLIENT_MODULE));
                const client = await connectEngine();
                try {
                    assert.deepEqual(await client.call('Echo', {value:42}), {value:42});
                    const items=[];
                    for await (const item of client.subscribe('Count')) items.push(item);
                    assert.deepEqual(items,[0,1]);
                    await assert.rejects(client.call('Missing'));
                    await assert.rejects(client.call('Never',{}, {timeoutMs:30}), /timed out/);
                    const abort = new AbortController();
                    const subscription = client.subscribe('Never', {}, {signal:abort.signal});
                    const waiting = subscription.next();
                    abort.abort();
                    await assert.rejects(waiting, /canceled/);
                } finally { client.close(); }
            "#,
            ])
            .env("TEST_CLIENT_MODULE", module)
            .env("CYPHER_ENGINE_SOCKET", path)
            .kill_on_drop(true)
            .output()
            .await
            .unwrap();
        server.abort();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
